services:
  - type: web
    name: youcaissepro
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install --prefix render-deploy && npm install --prefix render-deploy/backend
    startCommand: node render-deploy/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
